### ISSUE TITLE
Provide validation shapes for Observation

### ISSUE THREAD

**Issue by rob-metalinkage** [ternaustralia/ontology_tern#184] opened 2022-05-03 04:36 UTC
Currently the SHACL validation shapes require Observations to have mandatory fields, which may in future be better handled by ssn-extension ObservationCollection objects containing common metadata.

This has implications for three factors:

slimmer data transfer
more efficient validation
potential for more metadata about collections that are commonly applicable.
The proposal is to create two profiles of Tern:
1 "data at rest" - fully populated observations with all inherited collection attributes (similar to current shapes)
2 "compact exchange" - using Observation collections and allowing implicit properties to be checked against containing collections.

(it may also be worth examining the duplication of property shapes on sub-classes - possibly these are better inherited from parent superclasses and only modified where a sub-class has a specific requirement)

**Comment by dr-shorthair** [comment] 2022-05-03 04:39
Do you mean `ObservationCollection` ?
Or better still - provide conditional validation shapes for `Observation` as members of `ObservationCollection` .

**Comment by rob-metalinkage** [comment] 2022-05-03 07:31
dont know why the original description got dropped..

**Comment by edmondchuc** [comment] 2022-05-04 03:53
Closing this as a duplicate of https://github.com/ternaustralia/ontology_tern/issues/185

**Closed by edmondchuc** 2022-05-04 03:53 UTC
