### ISSUE TITLE
Ontology Legend

### ISSUE THREAD

**Issue by gwittich** [ternaustralia/ontology_tern#35] opened 2021-11-17 04:58 UTC
The legend at https://ternaustralia.github.io/ontology_tern/ lists the same acronym for ‘Data Properties’ and ‘Annotation Properties’, differentiated only by colour of font of acronym.

Gail Wittich - Gaia Resources

**Comment by dr-shorthair** [comment] 2021-11-19 05:12
I can't see what you are referring to here.

**Comment by nicholascar** [comment] 2021-12-06 03:00
The issue is that the superscript character indicator for both "Data Properties" and "Annotation Properties" is "dp". The second should be "ap".

This is a [pyLODE](https://github.com/rdflib/pylode) issue which I have reported here:

* https://github.com/RDFLib/pyLODE/issues/156

Also, this particular ontology is really documented at https://linkeddata-dev.tern.org.au/tern-ontology, and one presumes eventually, https://linkeddata.tern.org.au/tern-ontology, rather than https://ternaustralia.github.io/ontology_tern/. This point is itself the subject of Issue #41, also raised by @gwittich 

(@gwittich: you don't need to add your details to Issues as you post them, your GitHub account will tell us that!)

**Comment by edmondchuc** [comment] 2021-12-06 06:25
Closing as it is related to pyLODE and not the information model.

**Closed by edmondchuc** 2021-12-06 06:25 UTC
